### ISSUE TITLE
Is OpenIAB/OPFlab no more?  No more updates?

### ISSUE THREAD

**Issue by ne0ne2004** [onepf/OpenIAB-Unity-Plugin#102]
I just noticed this message on OpenIAB-Unity-Plugin and OPFlab home page:

>Dear friends
>
>Currently our small team doesn't have enough time to support and develop the project. I hope in the nearest future we will continue the work. Thank you!

https://github.com/onepf/OPFIab
https://github.com/onepf/OpenIAB-Unity-Plugin

Is there no more support for OpenIAB?

**Comment by RomanZhilich** [comment]
I hope I can manage OPFIab support on my free time. If there's a problem - create an issue. As for updates and new features... theres a lot to be done for sure but I'm not sure when the time come.
