### ISSUE TITLE
OpenIAB not working on Amazon Fire OS5 devices

### ISSUE THREAD

**Issue by mironal3x** [onepf/OpenIAB-Unity-Plugin#103]
I cannot get OpenIAB to work on Amazon Fire OS5 devices
I get the following error in the Android Device Monitor:

"01-13 15:32:23.569: I/Unity(11212): RetrieveProducts failed@In-App Purchases unavailable. Please login with a valid account and try again."

I checked with amazon to make sure the account I am trying to fetch the products with is valid.
Anyone else having this issue?

P.S: It works just fine on Amazon Fire OS4 devices

More details:
01-13 18:19:29.211: E/OpenIAB-UnityPlugin(23178): Problem setting up in-app billing: IabResult: 3, No suitable appstore was found (response: 3:Billing Unavailable)

I am using the following steps to build:
1. Connect the device to a Windows PC
2. Open cmd in Windows
3. cd "path to the .apk"
4. adb install -i com.amazon.venezia -r build.apk

**Comment by idubeda** [comment]
I have the same problem. I think it is related to [Amazon crash on Lollipop](https://github.com/onepf/OpenIAB/issues/433)
Perhaps the Lollipop patch doesn't work on Fire OS 5?
