### ISSUE TITLE
Amazone InApp integration

### ISSUE THREAD

**Issue by wasimjj** [onepf/OpenIAB-Unity-Plugin#39]
hi,
am running the demo scene for amazone ,but its is not Initialize

here is the code

if (Button ("Initialize OpenIAB")) {
						// Application public key
						var publicKey = "cfffdec9f06b4c279e561c7fc9e54d92";

						var options = new Options ();
						options.checkInventoryTimeoutMs = Options.INVENTORY_CHECK_TIMEOUT_MS * 2;
						options.discoveryTimeoutMs = Options.DISCOVER_TIMEOUT_MS * 2;
						options.checkInventory = false;
						options.verifyMode = OptionsVerifyMode.VERIFY_SKIP;
						options.prefferedStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.availableStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.storeKeys = new Dictionary<string, string>{{OpenIAB_Android.STORE_AMAZON,publicKey}};
						//	options.storeKeys = new Dictionary<string, string> { {OpenIAB_Android.STORE_GOOGLE, publicKey} };
						options.storeSearchStrategy = SearchStrategy.INSTALLER_THEN_BEST_FIT;

						// Transmit options and start the service
						OpenIAB.init (options);
				}

**Comment by akarimova** [comment]
Hi @wasimjj 
1. Amazon doesn't require any public keys. RSA keys are applicable only to Google Play, SlideME, Yandex.Store and several others.
2. What is returned by the plugin as a result of setup?
3. Where did you get the mentioned public key?

**Comment by wasimjj** [comment]
okay replace the code but still same nor working 

here is the code


private void Start ()
		{
				// Map skus for different stores       
				OpenIAB.mapSku (SKU, OpenIAB_Android.STORE_AMAZON, "amazon.sku_repair_kit");
				
				
		}



if (Button ("Initialize OpenIAB")) {
						// Application public key
						//var publicKey = "cfffdec9f06b4c279e561c7fc9e54d92";

						var options = new OnePF.Options ();
						options.checkInventory = false;
						options.prefferedStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.verifyMode = OptionsVerifyMode.VERIFY_ONLY_KNOWN;
						options.prefferedStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.availableStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.storeSearchStrategy = SearchStrategy.INSTALLER;
						// Transmit options and start the service
						OpenIAB.init (options);
				}




and here is error



01-07 22:28:15.769: D/dalvikvm(15480): GC_CONCURRENT freed 430K, 4% free 15928K/16455K, paused 1ms+1ms
01-07 22:28:16.207: E/NativeActivity(15480): channel '41f86ef0 com.muffinapps.learningwithstars/com.unity3d.player.UnityPlayerNativeActivity (client)' ~ Failed to receive dispatch signal.  status=-11
01-07 22:28:16.309: E/NativeActivity(15480): channel '41f86ef0 com.muffinapps.learningwithstars/com.unity3d.player.UnityPlayerNativeActivity (client)' ~ Failed to receive dispatch signal.  status=-11
01-07 22:28:16.324: D/OpenIAB-UnityPlugin(15480): createBroadcasts
01-07 22:28:16.324: D/OpenIAB-UnityPlugin(15480): Starting setup.
01-07 22:28:16.324: D/OpenIAB-UnityPlugin(15480): Setup finished.
01-07 22:28:16.324: E/OpenIAB-UnityPlugin(15480): Problem setting up in-app billing: IabResult: 3, No suitable appstore was found (response: 3:Billing Unavailable)
01-07 22:28:16.340: I/Unity(15480): billingNotSupportedEvent: No suitable appstore was found (response: 3:Billing Unavailable)
01-07 22:28:16.340: I/Unity(15480):  
01-07 22:28:16.340: I/Unity(15480): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
01-07 22:28:18.269: D/dalvikvm(205): GC_CONCURRENT freed 1292K, 18% free 20272K/24583K, paused 2ms+5ms

**Comment by wasimjj** [comment]
code


private void Start ()
		{
				// Map skus for different stores       
				OpenIAB.mapSku (SKU, OpenIAB_Android.STORE_AMAZON, "amazon.sku_repair_kit");
				
				
		}

				if (Button ("Initialize OpenIAB")) {
						// Application public key
						//var publicKey = "cfffdec9f06b4c279e561c7fc9e54d92";

						var options = new OnePF.Options ();
						options.checkInventory = false;
						options.prefferedStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.verifyMode = OptionsVerifyMode.VERIFY_ONLY_KNOWN;
						options.prefferedStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.availableStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
						options.storeSearchStrategy = SearchStrategy.INSTALLER;
						// Transmit options and start the service
						OpenIAB.init (options);
				}

**Comment by wasimjj** [comment]
download ther amazone tester apk and also put the jason /mnt/sdcard

**Comment by akarimova** [comment]
Let's change SearchStrategy.INSTALLER to SearchStrategy.INSTALLER_THEN_BEST_FIT. Otherwise you have to install your app using ``adb``  
E.g. ``adb install -i com.amazon.venezia your_package``.
Do not try to do anything with VerifyMode - it doesn't affect Amazon at all. 

Our team is on vacation (01.01 - 11.01), so we can't help ASAP as usual.

**Comment by wasimjj** [comment]
okay thank you for amazing supprt

**Comment by quinnhoener** [comment]
We're trying to integrate Amazon IAP into our app and having troubles. 

We have all the listeners setup, we're getting the `queryInventorySucceededEvent`, but it's returning an empty Inventory object. Not null, we are able to trace out that it has 0 available SKUs from `inventory.GetAllAvailableSkus().Count`. Our IAP is setup as an Entitlement in the Amazon Developer Portal. And we've been testing using Amazon's Live App Testing service. When running the app on the Kindle Fire HD, the adb logcat is tracing out {purchaseMap:{},skuMap:{}} as the inventory object.

Today I even copy/pasted the lastest from this repository into my Unity project and it's doing as I described. 

We're using Unity 4.6.0. 

Has anyone been able to get this to work?

**Comment by akarimova** [comment]
@GrimReio  help please

**Comment by quinnhoener** [comment]
I learned something new this morning. I can try to buy the IAP and it functions correctly. Just seems like the query Inventory isn't working properly. Sadly I need to query inventory because we have to display the price before the user clicks to try to buy it. Hope that helps narrow down the search.

**Comment by akarimova** [comment]
@quinnhoener 
did you try out latest releases?
we cannot emulate a situation with inventory problems.

**Comment by quinnhoener** [comment]
I tried based on the 0.9.8.4 release that was in the repository on Feb 3rd. Sorry to say, but we moved to Unibill framework. Maybe it was just a problem with our setup, thank you for your support.
