### ISSUE TITLE
Android 5 crashing

### ISSUE THREAD

**Issue by Spide** [onepf/OpenIAB-Unity-Plugin#40]
Hi, i have latest version of plugin 0.9.8 and everytime im calling function OpenIAB.queryInventory() aplication is starting again. In Google play we have 1star reviews from people with nexus 5 and nexus 9 only so its probably related to android 5, in older versions its workin fine.
Any chance to solve it ?

**Comment by GrimReio** [comment]
Could you please post some logs for this event?

**Comment by Spide** [comment]
Ok, how can i get it ? :)

**Comment by GrimReio** [comment]
You can use Android Studio IDE or [logcat](http://developer.android.com/tools/help/logcat.html) tool.

**Comment by Spide** [comment]
I think it should be here somewhere:

D/Finsky  (22968): [11426] InAppBillingUtils.pickAccount: com.maddreamfactory.wi
lyweedgame: Account determined from installer data - [73qEAqCw_GkZ9rK60EKHa60dOD
Q]
D/Finsky  (22968): [11452] InAppBillingUtils.pickAccount: com.maddreamfactory.wi
lyweedgame: Account determined from installer data - [73qEAqCw_GkZ9rK60EKHa60dOD
Q]
I/ElegantRequestDirector(22968): I/O exception (org.apache.http.NoHttpResponseEx
ception) caught when processing request: The target server failed to respond
I/ElegantRequestDirector(22968): Retrying request
D/Volley  (22968): [11435] DiskBasedCache.put: Could not clean up file /data/dat
a/com.android.vending/cache/main/14110868541696572915
D/Finsky  (22968): [11426] InAppBillingUtils.pickAccount: com.maddreamfactory.wi
lyweedgame: Account determined from installer data - [73qEAqCw_GkZ9rK60EKHa60dOD
Q]
D/OpenIAB-UnityPlugin( 9577): Query inventory finished.
D/OpenIAB-UnityPlugin( 9577): Query inventory was successful.
I/Unity   ( 9577): queryInventorySucceededEvent: {purchaseMap:{"levelpack1and2":
{SKU:levelpack1and2;{"orderId":"12999763169054705758.1349704424166324","packageN
ame":"com.maddreamfactory.wilyweedgame","productId":"levelpack1and2","purchaseTi
me":1404883963983,"purchaseState":0,"purchaseToken":"lendlgoilncmcnohdjnddoke.AO
-J1Ow-R9EEcl9RqImeJJxKwCYhkN8C0yEGn8MhGbSicIvuMg5LyMDRPmcxjXoCEybUho4bqY7OEt4o6j
2xLsvpq3RC2X9JWQw6CuGDGNOvy1EMzf8WHLdCVLCshdcIHmsHMTk5xKExL2SHNTcaHhJ2E4uIzRbQrQ
"}},},skuMap:{"levelpack1and2":{[SkuDetails: type = inapp, SKU = levelpack1and2,
 title = levelpack 1 a 2 (Wily weed), price = 30,00┬áK─Ź, description = levelpac
k 1 a 2, priceValue=30, currency=CZK]},}}
I/Unity   ( 9577):
I/Unity   ( 9577): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 49)
I/Unity   ( 9577):
I/WindowState(  628): WIN DEATH: Window{2b2d96ef u0 com.maddreamfactory.wilyweed
game/com.unity3d.player.UnityPlayerProxyActivity}
W/InputDispatcher(  628): channel '12fbd2a6 com.maddreamfactory.wilyweedgame/com
.unity3d.player.UnityPlayerNativeActivity (server)' ~ Consumer closed input chan
nel or an error occurred.  events=0x9
E/InputDispatcher(  628): channel '12fbd2a6 com.maddreamfactory.wilyweedgame/com
.unity3d.player.UnityPlayerNativeActivity (server)' ~ Channel is unrecoverably b
roken and will be disposed!
I/WindowState(  628): WIN DEATH: Window{fb9d36d u0 SurfaceView}
I/Sensors (  222): db ptr NULL OR string ID not valid (7)
I/Sensors (  222): db ptr NULL OR string ID not valid (8)
I/Sensors (  222): db ptr NULL OR string ID not valid (7)
I/Sensors (  222): db ptr NULL OR string ID not valid (8)
I/WindowState(  628): WIN DEATH: Window{12fbd2a6 u0 com.maddreamfactory.wilyweed
game/com.unity3d.player.UnityPlayerNativeActivity}
W/InputDispatcher(  628): Attempted to unregister already unregistered input cha
nnel '12fbd2a6 com.maddreamfactory.wilyweedgame/com.unity3d.player.UnityPlayerNa
tiveActivity (server)'
I/Zygote  (  214): Process 9577 exited due to signal (11)
I/ActivityManager(  628): Process com.maddreamfactory.wilyweedgame (pid 9577) ha
s died
W/ActivityManager(  628): Force removing ActivityRecord{29538e64 u0 com.maddream
factory.wilyweedgame/com.unity3d.player.UnityPlayerNativeActivity t159}: app die
d, no saved state
I/ActivityManager(  628): Start proc com.maddreamfactory.wilyweedgame for activi
ty com.maddreamfactory.wilyweedgame/com.unity3d.player.UnityPlayerProxyActivity:
 pid=10680 uid=10131 gids={50131, 9997, 3003} abi=armeabi-v7a
I/Timeline(10680): Timeline: Activity_launch_request id:com.maddreamfactory.wily
weedgame time:142607291
I/ActivityManager(  628): START u0 {flg=0x10000 cmp=com.maddreamfactory.wilyweed
game/com.unity3d.player.UnityPlayerNativeActivity} from uid 10131 on display 0
E/Vold    (  189): Failed to find mounted volume for /storage/usbdisk/Android/ob
b/com.maddreamfactory.wilyweedgame/
W/Vold    (  189): Returning OperationFailed - no handler for errno 0
W/ContextImpl(10680): Failed to ensure directory: /storage/usbdisk/Android/obb/c
om.maddreamfactory.wilyweedgame
E/Vold    (  189): Failed to find mounted volume for /storage/usbdisk/Android/da
ta/com.maddreamfactory.wilyweedgame/files/
W/Vold    (  189): Returning OperationFailed - no handler for errno 0
W/ContextImpl(10680): Failed to ensure directory: /storage/usbdisk/Android/data/
com.maddreamfactory.wilyweedgame/files
W/InputMethodManagerService(  628): Got RemoteException sending setActive(false)
 notification to pid 9577 uid 10131
I/ActivityManager(  628): Displayed com.maddreamfactory.wilyweedgame/com.unity3d
.player.UnityPlayerNativeActivity: +264ms (total +422ms)
I/Timeline(10680): Timeline: Activity_idle id: android.os.BinderProxy@35189f95 t
ime:142607615
I/Timeline(10680): Timeline: Activity_idle id: android.os.BinderProxy@377fa325 t
ime:142607617
I/Timeline(  628): Timeline: Activity_windows_visible id: ActivityRecord{3b8dbec
6 u0 com.maddreamfactory.wilyweedgame/com.unity3d.player.UnityPlayerNativeActivi
ty t159} time:142607729
I/Adreno-EGL(10680): <qeglDrvAPI_eglInitialize:410>: QUALCOMM Build: 10/28/14, c
33033c, Ia6306ec328

**Comment by GrimReio** [comment]
Are you sure this issue is related to the library?
Inventory is successfully queried.
```
D/OpenIAB-UnityPlugin( 9577): Query inventory finished.
D/OpenIAB-UnityPlugin( 9577): Query inventory was successful.
I/Unity ( 9577): queryInventorySucceededEvent: {purchaseMap:{"levelpack1and2":
{SKU:levelpack1and2;{"orderId":"12999763169054705758.1349704424166324","packageN
ame":"com.maddreamfactory.wilyweedgame","productId":"levelpack1and2","purchaseTi
me":1404883963983,"purchaseState":0,"purchaseToken":"lendlgoilncmcnohdjnddoke.AO
-J1Ow-R9EEcl9RqImeJJxKwCYhkN8C0yEGn8MhGbSicIvuMg5LyMDRPmcxjXoCEybUho4bqY7OEt4o6j
2xLsvpq3RC2X9JWQw6CuGDGNOvy1EMzf8WHLdCVLCshdcIHmsHMTk5xKExL2SHNTcaHhJ2E4uIzRbQrQ
"}},},skuMap:{"levelpack1and2":{[SkuDetails: type = inapp, SKU = levelpack1and2,
title = levelpack 1 a 2 (Wily weed), price = 30,00┬áK─Ź, description = levelpac
k 1 a 2, priceValue=30, currency=CZK]},}}
```
What is done in your query handler or right after that?

**Comment by Spide** [comment]
Oh, you are right i actualy found that. I had bug in queryInventorySucceededEvent, I called there some method from undefined object. Strange is that this problem is only on android 5.

Thank a lot for your help ;)

**Comment by GrimReio** [comment]
Don't mention it =)
