### ISSUE TITLE
How to verify purchases on Google Play on Unity

### ISSUE THREAD

**Issue by sp-miguel-janer** [onepf/OpenIAB-Unity-Plugin#43]
Hi!
I'm trying to figure how can I validate purchases from google play like this: https://github.com/onepf/OpenIAB/wiki/Google-Play#test
On the unity plugin I have no events/callbacks like that and no acces to the OpenIabHelper
thanks for your work :) it's awesome

**Comment by thuydx55** [comment]
OpenIab already provided us events in `OpenIABEventManager`

You can use `purchaseSucceededEvent` or `consumePurchaseSucceededEvent` event to get `Purchase`. Use `Purchase.OriginalJson` and `Purchase.Signature` for server side verification on Google Play

**Comment by sp-miguel-janer** [comment]
thanks :)

**Comment by akarimova** [comment]
Ups, sorry about the silence. No notifications about the issue:(
@thuydx55  thank you for the answer.

@sp-miguel-janer 
also you could use ``verifyMode``
like
``options.verifyMode = OptionsVerifyMode.VERIFY_ONLY_KNOWN;``
Please read [here]( https://github.com/onepf/OpenIAB-Unity-Plugin/blob/fd58019fb25f74e9d883cdd0442ff3557bb71d7a/unity_plugin/unity_src/Assets/Plugins/OpenIAB/OptionsVerifyMode.cs) about the mode.
