### ISSUE TITLE
OpenIAB not working on IOS.

### ISSUE THREAD

**Issue by minhit1805** [onepf/OpenIAB-Unity-Plugin#45]
After create items from itunesconnect.apple.com
In my Unity project i call:
const string noads_item2 = "2noads_item";
const string x2coin_item_stt_1 = "2x2coin_item_stt_2";
Start()
{
	OpenIAB.mapSku(noads_item2, OpenIAB_iOS.STORE, noads_item2);
	OpenIAB.mapSku (x2coin_item_stt_1, OpenIAB_iOS.STORE, x2coin_item_stt_1);
}
Void OnMouseDown()
{
    if(gameobject.name=="removead_btn")
    {
    OpenIAB.purchaseProduct (noads_item2);
    }
    else if(gameobject.name=="x2coin_btn")
    {
    OpenIAB.purchaseProduct (x2coin_item_stt_1);
    }
}
then i build this example project by xcode 6(add Storekit framework) to ipa and then install to my iphone device but still get no effect, what i was wrong here? *sorry for my bad english if something wrong*

**Comment by GrimReio** [comment]
Hello,

Do you call ```init``` somewhere?

**Comment by minhit1805** [comment]
This you mean OpenIAB.init(options)?, i think it's work only on android so because IOS have no publickey to add to options. so i no add this to my project.

**Comment by GrimReio** [comment]
Yes, this call is needed on iOS too. It creates list of SKUs internally.

**Comment by minhit1805** [comment]
var publicKey = "MIIBdhgdshFAAOCAQasfasfqibEPHCtfPm3Rn26gbE6vhCc1d6A072im+ddZ";
	

		var options = new Options ();
		options.checkInventoryTimeoutMs = Options.INVENTORY_CHECK_TIMEOUT_MS * 2;
		options.discoveryTimeoutMs = Options.DISCOVER_TIMEOUT_MS * 2;
		options.checkInventory = false;
		options.verifyMode = OptionsVerifyMode.VERIFY_SKIP;
		options.prefferedStoreNames = new string[] {
			OpenIAB_Android.STORE_GOOGLE,
			OpenIAB_Android.STORE_AMAZON,
			OpenIAB_Android.STORE_YANDEX
		};
		options.storeKeys = new Dictionary<string, string> { {OpenIAB_Android.STORE_GOOGLE, publicKey} };
		options.storeKeys = new Dictionary<string, string> { {OpenIAB_Android.STORE_AMAZON, publicKey} };
		 Transmit options and start the service
		OpenIAB.init (options);
but i can't add OpenIAB.init with null options because i have no publickey on ituneconnect.apple.com page. what is options value on ios?

**Comment by GrimReio** [comment]
You can call ```OpenIAB.init()``` or pass same options as for android.

**Comment by minhit1805** [comment]
OpenIAB.init() get error No overload for method "init" takes '0' argument, i will try with options as for android and remove some line code look like: 
  var options = new Options ();
    options.checkInventoryTimeoutMs = Options.INVENTORY_CHECK_TIMEOUT_MS * 2;
    options.discoveryTimeoutMs = Options.DISCOVER_TIMEOUT_MS * 2;
    options.checkInventory = false;
    options.verifyMode = OptionsVerifyMode.VERIFY_SKIP;
    options.prefferedStoreNames = new string[] {
        OpenIAB_Android.STORE_GOOGLE,
        OpenIAB_Android.STORE_AMAZON,
        OpenIAB_Android.STORE_YANDEX
    };

    OpenIAB.init (options);

**Comment by GrimReio** [comment]
Well, this line indicates that purchase was successful:
```purchaseSucceededEvent: SKU:2x2coin_item_stt_2;```

Did you subscribe to the OpenIAB events?

**Comment by minhit1805** [comment]
What do you mean? i was not change anything and use this:
	
	private void purchaseFailedEvent(int errorCode, string errorMessage)
	{
		Debug.Log("purchaseFailedEvent: " + errorMessage);
		_label = "Purchase Failed: " + errorMessage;
	}
	private void consumePurchaseSucceededEvent(Purchase purchase)
	{
		Debug.Log("consumePurchaseSucceededEvent: " + purchase);
		_label = "CONSUMED: " + purchase.ToString();
	}
	private void consumePurchaseFailedEvent(string error)
	{
		Debug.Log("consumePurchaseFailedEvent: " + error);
		_label = "Consume Failed: " + error;
	}

**Comment by GrimReio** [comment]
There is an example of event handling. Did you do something like this?
```
    private void OnEnable()
    {
        // Listen to all events for illustration purposes
        OpenIABEventManager.billingSupportedEvent += billingSupportedEvent;
        OpenIABEventManager.billingNotSupportedEvent += billingNotSupportedEvent;
        OpenIABEventManager.queryInventorySucceededEvent += queryInventorySucceededEvent;
        OpenIABEventManager.queryInventoryFailedEvent += queryInventoryFailedEvent;
        OpenIABEventManager.purchaseSucceededEvent += purchaseSucceededEvent;
        OpenIABEventManager.purchaseFailedEvent += purchaseFailedEvent;
        OpenIABEventManager.consumePurchaseSucceededEvent += consumePurchaseSucceededEvent;
        OpenIABEventManager.consumePurchaseFailedEvent += consumePurchaseFailedEvent;
    }
```

**Comment by GrimReio** [comment]
Also an instance of ```OpenIABEventManager``` should be in the scene.

**Comment by minhit1805** [comment]
sure, this code working good on android.
   private void purchaseSucceededEvent(Purchase purchase)
	{
		Debug.Log("purchaseSucceededEvent: " + purchase);
		_label = "PURCHASED:" + purchase.ToString();
		switch (purchase.Sku) { 
			// control product and price here;
		case noads_item: 
		{
			GameObject endIAP;
			PlayerPrefs.SetInt("isnoadsdata",1);
		}
			break;
		case x2coin_item_stt_1: 
			PlayerPrefs.SetInt("isdoublegold",1);
			break; 
		default:
			Debug.LogWarning ("UnknownSKU: " + purchase);
			break;
		}
	}
	private void purchaseFailedEvent(int errorCode, string errorMessage)
	{
		Debug.Log("purchaseFailedEvent: " + errorMessage);
		_label = "Purchase Failed: " + errorMessage;
	}
	private void consumePurchaseSucceededEvent(Purchase purchase)
	{
		Debug.Log("consumePurchaseSucceededEvent: " + purchase);
		_label = "CONSUMED: " + purchase.ToString();
	}
	private void consumePurchaseFailedEvent(string error)
	{
		Debug.Log("consumePurchaseFailedEvent: " + error);
		_label = "Consume Failed: " + error;
	}
	private void OnEnable()
	{
		// Listen to all events for illustration purposes
		OpenIABEventManager.billingSupportedEvent += billingSupportedEvent;
		OpenIABEventManager.billingNotSupportedEvent += billingNotSupportedEvent;
		OpenIABEventManager.queryInventorySucceededEvent += queryInventorySucceededEvent;
		OpenIABEventManager.queryInventoryFailedEvent += queryInventoryFailedEvent;
		OpenIABEventManager.purchaseSucceededEvent += purchaseSucceededEvent;
		OpenIABEventManager.purchaseFailedEvent += purchaseFailedEvent;
		OpenIABEventManager.consumePurchaseSucceededEvent += consumePurchaseSucceededEvent;
		OpenIABEventManager.consumePurchaseFailedEvent += consumePurchaseFailedEvent;
	}
	private void OnDisable()
	{
		// Remove all event handlers
		OpenIABEventManager.billingSupportedEvent -= billingSupportedEvent;
		OpenIABEventManager.billingNotSupportedEvent -= billingNotSupportedEvent;
		OpenIABEventManager.queryInventorySucceededEvent -= queryInventorySucceededEvent;
		OpenIABEventManager.queryInventoryFailedEvent -= queryInventoryFailedEvent;
		OpenIABEventManager.purchaseSucceededEvent -= purchaseSucceededEvent;
		OpenIABEventManager.purchaseFailedEvent -= purchaseFailedEvent;
		OpenIABEventManager.consumePurchaseSucceededEvent -= consumePurchaseSucceededEvent;
		OpenIABEventManager.consumePurchaseFailedEvent -= consumePurchaseFailedEvent;
	}	
	private void billingSupportedEvent()
	{
		//_isInitialized = true;
		Debug.Log("billingSupportedEvent");
	}
	private void billingNotSupportedEvent(string error)
	{
		Debug.Log("billingNotSupportedEvent: " + error);
	}
	private void queryInventorySucceededEvent(Inventory inventory)
	{
		Debug.Log("queryInventorySucceededEvent: " + inventory);
		if (inventory != null)
			_label = inventory.ToString();
	}
	private void queryInventoryFailedEvent(string error)
	{
		Debug.Log("queryInventoryFailedEvent: " + error);
		_label = error;
	}

**Comment by GrimReio** [comment]
Could you please post full log from XCode?

**Comment by minhit1805** [comment]
How to get this log? i build this project to IPA file then install to my iphone 5s without run on my xcode 6.

**Comment by GrimReio** [comment]
Take it from Unity then, i guess. Should be same.

**Comment by minhit1805** [comment]
sorry for my delay, i lost a lot of time to take screenshot on my mac, this is my unity debug log when i click removead button:
![s1](https://cloud.githubusercontent.com/assets/9863542/5959020/0d8871a4-a7fd-11e4-9310-faf1fe8a0f8b.png)

**Comment by GrimReio** [comment]
If this is log when you run in the editor mode, then it's irrelevant. I thought, you somehow connected Unity debugger to the device.
You can choose either to build and run directly to device from XCode or use Organizer, like here ![Device Logs](http://take.ms/m5fb9)

**Comment by minhit1805** [comment]
this is my log when run my game:
Jan 29 21:50:29 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235829.794658]: Client itunesstored set type to background application
Jan 29 21:50:29 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235829.797370]: BG Application: Present, BG Daemon: Present. Daemons: assistantd apsd sharingd networkd itunesstored 
Jan 29 21:50:29 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235829.799084]: Already connected to obuuttech2.
Jan 29 21:50:37 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235837.016363]: Client itunesstored set type to normal application
Jan 29 21:50:37 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235837.017383]: BG Application: Present, BG Daemon: Present. Daemons: assistantd apsd sharingd networkd 
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.083562]: WiFiLocaleManagerCheckLocale: trying to determine locale...
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.084279]: WiFiManagerCoreLocationGetCachedLocation: getting cached location...
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.087248]: __WiFiLocaleManagerGetLocaleFromMcc: finding iso country code for mcc 452 ....
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.087798]: Starting Low Accuracy Location Monitoring, locationMonitoringTimeout=60.000000
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.088128]: WiFiManagerCoreLocationStartLocationUpdates: starting location updates...
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.089395]: Location Monitoring successfully started with accuracy=3000.000000meters
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.089753]: __WiFiLocationServiceManagerEventCallback, got cb dict <dictionary> {
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>:   eventType : 0
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>:   location : <+10.78433107,+106.68324882> +/- 957.62m (speed -1.00 mps / course -1.00) @ 1/29/15, 9:50:58 PM Indochina Time
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: }
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.095038]: __WiFiLocationServiceManagerProcessLocationAvailableEvent: isValidHighAccuracyLocation 0,  isValidLowAccuracyLocation 1
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.095370]: __WiFiLocationServiceManagerProcessLocationAvailableEvent: give low accuracy callback
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.096036]: __WiFiLocaleManagerGetLocaleFromLocation: <+10.78433107,+106.68324882> +/- 957.62m (speed -1.00 mps / course -1.00) @ 1/29/15, 9:50:58 PM Indochina Time
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.099853]: locale from bounding box 
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.100128]: new locale:  , locale: 
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.100398]: Stopping Low Accuracy Location Monitoring
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.100710]: Location Monitoring stopped
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.100985]: WiFiManagerCoreLocationStopLocationUpdates: stopping location updates...
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.101326]: Stopping Low Accuracy Location Monitoring
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.101628]: CLMonitoring is already stopped
Jan 29 21:50:58 Minhit--iPhone wifid[15] <Notice>: WiFi:[444235858.630578]: WoW is Enabled, 1 WoW Clients

**Comment by minhit1805** [comment]
********** iOS OpenIAB plugin initialized **********
 
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

billingSupportedEvent
 
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

purchaseFailedEvent: Cannot connect to iTunes Store
 
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

**Comment by GrimReio** [comment]
I'm sorry, but I think, this issue is unrelated to the library.
Something is wrong with the store setup.
Maybe try something from this [article](http://support.apple.com/en-us/HT201400).

**Comment by minhit1805** [comment]
oh thanks you very much for cost a lot of time to help me. I found this issues https://github.com/onepf/OpenIAB/issues/209 and will try your suggest. 

but what wrong if i use this options: 
var options = new Options ();
options.checkInventoryTimeoutMs = Options.INVENTORY_CHECK_TIMEOUT_MS * 2;
options.discoveryTimeoutMs = Options.DISCOVER_TIMEOUT_MS * 2;
options.checkInventory = false;
options.verifyMode = OptionsVerifyMode.VERIFY_SKIP;
options.prefferedStoreNames = new string[] {
OpenIAB_Android.STORE_GOOGLE,
OpenIAB_Android.STORE_AMAZON,
OpenIAB_Android.STORE_YANDEX
};
OpenIAB.init (options);

**Comment by GrimReio** [comment]
No problem. I'll close this issue for now. Feel free to contact me if there will be other problems after store setup.

**Comment by NitinParmar7** [comment]
I am having same problem - Cannot connect to itunes store
 I have called Init too
