### ISSUE TITLE
Amazon iap 1.0 and 2.0 mixed attributes

### ISSUE THREAD

**Issue by gperretti** [onepf/OpenIAB-Unity-Plugin#49]
Hi all.

Im a bit confused.
OpenIAB is using the in-app-purchasing-2.0.1. But still is receiving responses as you are using the  in-app-purchasing-1.x.
I mind:
After doing a purchase, the response is: 
{"purchaseToken":"xxxxx","purchaseStatus":"SUCCESSFUL","orderId":"xxxxx","itemType":"CONSUMABLE","userId":"xxxxx","productId":"xxxxx"}

but according to https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/migrate-iapv1-apps-to-iapv2

purchaseToken should call receiptId (seems like your using v1.x)
BUT
your using productId instead of sku (seems your using v2.x)

Then, there are a mix of v1.x and v.2.x attributes and im getting errors on verify the purchase on amazon servers.

Any light you can shed here?  Thanks!!!

**Comment by RomanZhilich** [comment]
Hello.

The JSON you refer to is not directly returned by Amazon, instead it's handled by OpenIAB library and turned into java object. Then it's converted back to JSON by Unity Plugin. Thus, JSON fields you get from plugin differ from ones declared in Amazon API.

**Comment by gperretti** [comment]
Hi, Roman, thanks for the response.

Then OpenIAB is using the v2.0 right? I need to send the "receiptId" field to the server, to validate the purchase. Which field should I use or "receiptId" is not returned by the plugin?

**Comment by RomanZhilich** [comment]
> Then OpenIAB is using the v2.0 right?

Yes, we use amazon-iab-2.0.1
> Which field should I use or "receiptId" is not returned by the plugin

receiptId should be returned as "purchaseToken"

**Comment by gperretti** [comment]
Thanks. ill try and let you know!

**Comment by gperretti** [comment]
Great its working, thank!!!

**Comment by RomanZhilich** [comment]
Glad it worked out.
