### ISSUE TITLE
Events are not being triggered

### ISSUE THREAD

**Issue by Nesokas** [onepf/OpenIAB-Unity-Plugin#51]
I'm trying to use openIAB unity plugin but the events are not being triggered. I have the following code equal to the examples and none of the events are called:

private void OnEnable()
	{
		// Listen to all events for illustration purposes
		OpenIABEventManager.billingSupportedEvent += billingSupportedEvent;
		OpenIABEventManager.queryInventorySucceededEvent += queryInventorySucceededEvent;
		OpenIABEventManager.purchaseSucceededEvent += purchaseSucceededEvent;
		OpenIABEventManager.purchaseFailedEvent += purchaseFailedEvent;
		OpenIABEventManager.consumePurchaseSucceededEvent += consumePurchaseSucceededEvent;
		OpenIABEventManager.consumePurchaseFailedEvent += consumePurchaseFailedEvent;
	}

Can someone tell me what I might be doing wrong?

**Comment by GrimReio** [comment]
Hello,

Could you please check that there is event listener in the scene and post some more code and logs from device?

**Comment by Nesokas** [comment]
Nevermind. This was dumb. Yes the event listener was missing.
