### ISSUE TITLE
java.lang.IllegalArgumentException while building (solved)

### ISSUE THREAD

**Issue by benuto** [onepf/OpenIAB-Unity-Plugin#74]
Hi,
I get this error while building the project:

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/android/vending/billing/IInAppBillingService$Stub$Proxy;

Unity 5.1.1f1
OpenIAB 0.9.8.6

I use the Google Admob plugin which requires the google_play_services_lib folder to be imported. I think this might be the cause of the problem.

**Comment by benuto** [comment]
Project works fine after reimporting all plugins.

**Comment by akarimova** [comment]
great!)
