### ISSUE TITLE
OpenIAB and Facebook SDK problem

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [onepf/OpenIAB-Unity-Plugin#79]
When I include your latest sdk and facebook sdk 7.0.2 then I get a linker error for duplicate symbols. your appsotredelegate.mm and their fbunityinterface.mm clash.
also in unity 5.1 it seems I need to add -fno-objc-arc to appstoredelegate.mm to be able to compile it and eitheradd storekit by hand or just tick it in unity's inspector as a dependency.

Is this all right about adding the flag and what can I do about the duplicate symbol linker error with the facebook file?

**Comment by hfarhan37** [comment]
facing same issue here. have you found any solution yet?

**Comment by ashkan-saeedi-mazdeh** [comment]
I ended up using facebook latest stable 6.x SDK and it worked. for IOS compilation you need to just add -fno-objc-arc to some files which you can find by a google search "compile unity 5 facebook sdk ios" are the keywords.
